# Generated by Django 4.2.30 on 2026-06-24 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_wallet_balance",
                    models.DecimalField(
                        decimal_places=2, default=2450.0, max_digits=12
                    ),
                ),
                (
                    "active_contract_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "verbose_name_plural": "App state",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=512)),
                ("user_role", models.CharField(max_length=64)),
                ("user_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ContractDetails",
            fields=[
                (
                    "contract_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("signed_date", models.DateTimeField()),
                ("expiry_date", models.DateTimeField()),
                ("sla_level", models.CharField(max_length=255)),
                ("billing_code", models.CharField(max_length=128)),
                ("max_concurrent_sessions", models.IntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("expired", "Expired")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("payment", "Payment"),
                            ("payout", "Payout"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(max_length=128)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("client_name", models.CharField(max_length=255)),
                (
                    "interpreter_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("language_from", models.CharField(max_length=64)),
                ("language_to", models.CharField(max_length=64)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("legal", "Legal"),
                            ("business", "Business"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "service_mode",
                    models.CharField(
                        choices=[("AI", "AI"), ("Human", "Human"), ("Both", "Both")],
                        default="Human",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("incoming", "Incoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_time",
                    models.CharField(blank=True, default="instant", max_length=64),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("duration_seconds", models.IntegerField(default=0)),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("rating_by_client", models.IntegerField(blank=True, null=True)),
                ("review_by_client", models.TextField(blank=True, default="")),
                ("emergency_triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interpreter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interpreter_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("client", "Client"),
                            ("interpreter", "Interpreter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("rating", models.FloatField(default=5.0)),
                ("completed_sessions", models.IntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=8),
                ),
                ("avatar", models.URLField(blank=True, default="")),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("interpreter", "Interpreter"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("translated_text", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InterpreterAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=20)),
                ("slots", models.JSONField(default=list)),
                (
                    "interpreter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interpreter availabilities",
                "unique_together": {("interpreter", "day")},
            },
        ),
    ]
