# Generated by Django 4.2.30 on 2026-06-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebRTCSignal",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[("client", "Client"), ("interpreter", "Interpreter")],
                        max_length=20,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("offer", "Offer"),
                            ("answer", "Answer"),
                            ("ice", "ICE Candidate"),
                            ("hangup", "Hangup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webrtc_signals",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
