# Generated by Django 4.2.30 on 2026-06-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_fix_webrtc_signal_id_default"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profile",
            new_name="api_profile_contrac_1bd00f_idx",
            old_name="api_profile_contract_role_idx",
        ),
    ]
